// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package domain

import (
	"errors"
	"fmt"
)

const (
	// GenderM is a Gender of type M.
	GenderM Gender = "M"
	// GenderF is a Gender of type F.
	GenderF Gender = "F"
)

var ErrInvalidGender = errors.New("not a valid Gender")

// String implements the Stringer interface.
func (x Gender) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Gender) IsValid() bool {
	_, err := ParseGender(string(x))
	return err == nil
}

var _GenderValue = map[string]Gender{
	"M": GenderM,
	"F": GenderF,
}

// ParseGender attempts to convert a string to a Gender.
func ParseGender(name string) (Gender, error) {
	if x, ok := _GenderValue[name]; ok {
		return x, nil
	}
	return Gender(""), fmt.Errorf("%s is %w", name, ErrInvalidGender)
}
